### PR TITLE
Prevent redirects from opening two tabs

### LINKED ISSUE #41: Two tabs with the same website are wrongly opened when trying to log in on it with Facebook, if the website was previously assigned to a container
**[Notes]:**
- If at step 2 the "Remember my decision for this site" option was not checked then the user will end with two confirmation windows.
- Even if you are not logged in to Facebook, after following the normal log in flow, you will encounter the same issue.

**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- You must be logged in to Facebook.
- Have the Firefox Multi-Account Containers add-on (6.0.0) installed.
- Have the any website assigned that has the "Log In with Facebook" option to any container (eg. https://9gag.com to Work).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://9gag.com and check the "Remember my decision for this site" option.
3. Press the "Open in Work Container" option.
4. Click the "Log In" button and select the "Facebook" option.
5. Observe the behavior.

**[Expected result]:**
- You are successfully logged in.

**[Actual result]:**
- You are successfully logged in but also two tabs with the same website are opened.

**[Additional Notes]:**
- The issue is reproducible with any website that has the "Log In with Facebook" option.
- Attached a screen recording of the issue: 
rec of the issue

### LINKED ISSUE #48: Duplicate tabs opening
When a non-Facebook URL is typed into the address bar, the existing tab will go to the page but switch from the Facebook container to the default container. However, a duplicate tab will also open with that same URL.

### PR DESCRIPTION
**Pull request by stoically**
Applies the same patch as in https://github.com/mozilla/multi-account-containers/pull/1120

Fixes #48, Fixes #41

### CODE REVIEW

**Comment by groovecoder** [comment]
Since https://github.com/mozilla/contain-facebook/pull/64 is merged, this now has a conflict. But, these bugs/issues also seem to be fixed by https://github.com/mozilla/contain-facebook/pull/64, so I'm going to close this PR anyway.

**Comment by stoically** [comment]
The simple fix in #64 does not address the duplicate tab issues at all.

**Comment by stoically** [comment]
@groovecoder I've rebased this PR on #54 - so this PR could be merged without conflict after #54 is merged. Also, like already mentioned, neither #54 nor #64 address the duplicate tab issues reported in #48 and #41 - also, while working on that Issues, I've experience duplicate tabs myself. Also, @jonathanKingston mentioned on IRC the following:

> Cos the latest nightly I watched a friend replicate this with containers just a minute ago with duckduckgo->google with an assigned google

That's regarding MAC - so people still experience this problem with MAC too, since the merged patched in https://github.com/mozilla/multi-account-containers/pull/1120 isn't published yet.

I'v added the same patch to Temporary Containers a while ago and haven't experienced a duplicate tab since - so I'd recommend merging this PR.

**Comment by groovecoder** [comment]
Hmm ... I think you need to be the one to re-open the PR here? I can't seem to do it.

**Comment by groovecoder** [comment]
And yes - I just noticed the duplicate tab issue again on top of #54 and #64 merges.

**Comment by stoically** [comment]
Can't seem to reopen either - opened #68 instead.

**Pull request closed without merging**
