### PR TITLE
Send jailed domains

### PR DESCRIPTION
**Pull request by jonathanKingston**
Counter part commit: https://github.com/mozilla/multi-account-containers/pull/1188

### CODE REVIEW

**Comment by groovecoder** [comment]
Should we close this in favor of #128 ?

**Comment by stoically** [comment]
@jonathanKingston Looks good to me. I guess the only thing I noticed here and in https://github.com/mozilla/multi-account-containers/pull/1188 is the race-condition that can happen between setting up listeners and sending messages between MAC and FC (sendMessage on both sides) - like you already mentioned in https://github.com/mozilla/contain-facebook/issues/113#issuecomment-380444165

**Comment by jonathanKingston** [comment]
@stoically the chance here is minimal, however CF still checks the MAC assignments as before as well which means at worst the browser will open into a previously assigned container as a race condition whilst it is clearing. Also because of the "MACListening" message we should also clear out those assignments twice on MAC in most cases.

**Comment by jonathanKingston** [comment]
I added the MACListening after testing with the code mentioning in the #113 comment and then couldn't replicate the race condition ever due to the double clearing. If MAC updates to 7.0.0 after FC it still will inform FC that it is now listening etc.

**Comment by jonathanKingston** [comment]
Essentially we have three chances to get this right:
```
if (macAddonInfo.enabled) {
  sendJailedDomainsToMAC();
```
```
case "MACListening":
  sendJailedDomainsToMAC();
```
and the existing code that checks assignments (this should be removed eventually).

**Pull request merged**
