### PR TITLE
Disable extension in incognito mode

### PR DESCRIPTION
**Pull request by romanrodriguez**
The extension's functionality should resemble the Multi-Account Containers and be disabled in Incognito mode.

### CODE REVIEW

**Comment by maxxcrawford** [comment]
@arthur-mozilla Thoughts on this?

**Comment by romanrodriguez** [comment]
To clarify, as suggested by @groovecoder in https://github.com/mozilla/multi-account-containers/issues/930,  I submitted a pull request for each extention disabling them while in incognito mode.

**Comment by stoically** [comment]
Like mentioned over in the [MAC PR](https://github.com/mozilla/multi-account-containers/pull/1512#issuecomment-540994018), we probably want to set `strict_min_version` to 67 so the Add-on doesn't break for users on version 66.

**Comment by romanrodriguez** [comment]
Hi @maxxcrawford, I've extended work on this in a new pull request ( #535 ). Thanks!

**Pull request merged**
