### PR TITLE
Use single svg icon instead of 2 png icons

### PR DESCRIPTION
**Pull request by trevorhobson**
Convert the icon from png to svg

### CODE REVIEW

**Comment by esaruoho** [comment]
could this be merged in @groovecoder @groovecoder-mozilla-owner

**Comment by groovecoder** [comment]
I'll take a look ... but it won't be as high priority as the `fbclid` PR.

**Comment by esaruoho** [comment]
@groovecoder  cool! just saw the `fbclid` #179 land, so.. this is next? :)

**Comment by groovecoder** [comment]
Maybe. checking with @ryanfeeley for the original source `.svg` file so I may send my own PR with the original `.svg` instead of this (presumably) converted SVG.

**Comment by groovecoder** [comment]
Superseding this with https://github.com/mozilla/contain-facebook/pull/181 which includes svg file from Mozilla design team.

**Pull request closed without merging**
