### PR TITLE
added cdninstagram.com to the list of facebook domains

### PR DESCRIPTION
**Pull request by panzi**

### CODE REVIEW

**Comment by panzi** [comment]
Looking at all the unmerged pull requests: Is this project dead?

**Comment by SoftVision-PaulOiegas** [comment]
@panzi I wouldn't say that just yet. It's just that the developers are involved in other projects too. Will probably return once they have some time to spare.

**Comment by NewAlexandria** [comment]
@SoftVision-PaulOiegas that’s hard to stomach.  These are literally additions of known domains

**Comment by SoftVision-PaulOiegas** [comment]
@NewAlexandria Hey, yes I know. The dev team was planning to add more stuff to the add-on. But for now the development was paused indefinitely for some reasons that I don't know.

However, if you have the knowledge you can built yourself the add-on containing all the changes you want since this project is open source. And after use the `xpinstall.signatures.required` on `false` in order to install it afterwards, since it won't be signed.

**Comment by NewAlexandria** [comment]
@SoftVision-PaulOiegas thanks for the encouragement to build.  My mind was already in that direction.

Can you give me any tips on how to seek-out the team or decision-makers around this?  A security add-on like this seems important to develop properly.  It's also easy to think that people were asked to stop working on it because of the broad impact it can have on monetization by online media companies.  As much as that is unpopular, it is a form of lobbying that was effective at neutralizing Ghostery and others.

**Comment by NewAlexandria** [comment]
Along the lines of OSS development, the logic also needs to be updated, to use partial matches rather than exact matches.  An exact-match list would be too long to maintain.  I know there is a performance issue that comes eventually, but a list of ever-growing blacklisted domains doesn't seem viable.

**Comment by NewAlexandria** [comment]
Along the lines of OSS development, the logic also needs to be updated, to use partial matches rather than exact matches.  An exact-match list would be too long to maintain.  I know there is a performance issue that comes eventually, but a list of ever-growing blacklisted domains doesn't seem viable.

**Comment by SoftVision-PaulOiegas** [comment]
@NewAlexandria If I recall right, @TanviHacks, @ryanfeeley, @groovecoder, @jonathanKingston are the people you are looking for.

**Comment by esaruoho** [comment]
@groovecoder - since Facebook owns Instagram, wouldn't it make sense to get this into the `contain-facebook` repo?

**Comment by groovecoder** [comment]
Yes, this change makes sense. But we saw some breakage when we first tried to add Instagram to the container, and we haven't had time to debug it. 😢 We are currently in the application phase of getting some help on the Containers project(s)/repo(s) via Mozilla's Outreach participation. (Mozilla project 5 on https://www.outreachy.org/apply/project-selection/)

**Comment by esaruoho** [comment]
@panzi could you fix this PR so that there are no file conflicts with `src/background.js` ? maybe rebase this branch on the current state of the `contain-facebook` repo and fix any conflicts?

**Comment by esaruoho** [comment]
@panzi could you fix the conflicts in this, or rebase the PR on the current state of the repo?

**Comment by panzi** [comment]
Ok, rebased my patch.

**Comment by esaruoho** [comment]
Hi @ShivangiKakkar - any chance you could have a look at this too?

https://github.co

**Comment by esaruoho** [comment]
Hi @ShivangiKakkar - any chance you could have a look at this too?

**Comment by esaruoho** [comment]
Hi @ShivangiKakkar - any chance you could have a look at this too?

**Comment by esaruoho** [comment]
@panzi github has been having some issues as of late, could you re-rebase? it's still showing conflicts. i think some branch commits or PR updates have gone missing due to github having.. issues..

**Comment by esaruoho** [comment]
Hi @ShivangiKakkar - any chance you could have a look at this too?

**Comment by esaruoho** [comment]
Hi @ShivangiKakkar - any chance you could have a look at this too? i think github works now so this message will go through and stay through, and stay posted, and not vanish..

**Comment by esaruoho** [comment]
thanks @panzi !

**Comment by esaruoho** [comment]
@groovecoder @groovecoder-mozilla-owner @jbuck-mozilla-owner @clouserw-mozilla-owner @jonathanKingston 

looks like this could be merged in, as long as maybe @ShivangiKakkar can have a look at it?

**Comment by esaruoho** [comment]
@panzi hi, your branch is again having conflicts that should be resolved. can you compare it with the current state of this `src/background.js` app, maybe the #175 getting merged in already includes your fixes, or..?

**Comment by esaruoho** [comment]
@panzi looking at https://github.com/mozilla/contain-facebook/blob/master/src/background.js current state, it already has the `"cdninstagram.com", "messengerdevelopers.com"`

that you wanted merged in. the messengerdevelopers.com already contains the blog.messengerdevelopers.com by default, so no need for that to be there (optimisation).. maybe this ticket could be closed since the repo already has your URLs?

**Comment by panzi** [comment]
Yes, if subdomains are automatically included then yes, this is all I wanted. :)

**Pull request closed without merging**
