### PR TITLE
Block outgoing Facebook cookies in all Non-Facebook Containers

### LINKED ISSUE #74: Regularly clear facebook cookies in other containers or strip them from subresources completely.
It looks like facebook cookies are only cleared when the extension is installed.

Since facebook is no longer usable in the default container cookies, we should probably still delete cookies every once in a while, to prevent logged-out tracking. Is this possible?

### PR DESCRIPTION
**Pull request by stoically**
Easy way to check: visit internet.org without this patch in Non-Facebook Container, check for www.facebook.com request in the DevTools, see cookie in the request header. Load with patch, repeat, cookie header gone

Rebased on #78 

Fixes #74

### CODE REVIEW

**Comment by groovecoder** [comment]
This is a good idea, but I'd like @TanviHacks to give some input. This starts to turn the add-on from "Containment" (e.g., like MAC) towards "Blocking" (e.g., like Privacy Badger).

**Comment by stoically** [comment]
Well, the Add-on description says `Prevent Facebook from tracking you around the web.`. This change makes sure that Facebook can't build a tracking profile based on Cookies in Non-Default Containers. Such a profile could at any point be leaked into the actual Facebook Account/Container, e.g. by clicking the "Login with Facebook" button somewhere.

**Comment by TanviHacks** [comment]
* Do any of the "login to facebook" flows work with the extension?
I think the answer is yes - when url parameters are used for the authentication flow.

* Would this change break that login flow?

* Do we want to continue to support those login flows, even though we know that Facebook can track activity that happens on those third parties?
I think yes - since the user is taking an explicit action to use Facebook with the third party.  The same way we wouldn't want to forcefully stop the user from installing a facebook app that extracts their facebook data.

On the other hand, since some of these login flows are broken anyway, maybe this breakage would be acceptable.

* Does this put us in the category as ad blockers?
Well, we aren't blocking anything.  But it does take us a bit further than Containment.

From a product standpoint, I'm not convinced one way or another yet.  Perhaps Cindy or @pdolanjski can chime in.  Are we going too far here?  Or is this what we need to do in order to mitigate facebook tracking?

**Comment by stoically** [comment]
>  Do any of the "login to facebook" flows work with the extension?
> Would this change break that login flow?
> Do we want to continue to support those login flows, even though we know that Facebook can track activity that happens on those third parties?

This change wouldn't affect "Login to Facebook" flows compared to what the Add-on is already doing. They now also only work if URL Parameters are used.

> Does this put us in the category as ad blockers?
> Well, we aren't blocking anything.

I'd say no because no ads are blocked.

> But it does take us a bit further than Containment.

One thing that should be considered: The Add-on already clears cookies on every initialization. The change would just consequently make sure that also after initialization Facebook Cookies aren't usable for tracking purposes after initialization.

**Comment by groovecoder** [comment]
I'd also like @pdolanjski and/or @chsiang to make a call here. FWIW I'm personally in favor of this change too. (Though it needs a rebase.)

**Comment by jonathanKingston** [comment]
I personally think this shouldn't be a default given the cookies are cleared anyway so should be meaningless but trackers. This could however be an options page setting though.

**Comment by groovecoder** [comment]
As an aside/bike-shed ... I've often wondered if the better privacy strategy is NOT to block cookies. Let me explain ...

In [the Privacy Settings Breakage Study](https://docs.google.com/presentation/d/1OVtXAnyeBLX2N1yyZoTMP9AV_6HnI3mnXwIFlOL7yOA/edit), we saw a number of users reporting that websites told them their cookies were disabled. This suggests that many sites detect when cookies are blocked, and react accordingly. I wonder if blocking cookies might trigger code on the part of trackers to use other, cookie-less tracking mechanisms - e.g., fingerprinting.

If that's what's happening, in this case it may be best to keep sending cookies AND keep wiping them on every browser restart? That way, tracking code using the cookies will see dozens of different cookies. And that may add "noise" in their system that's actually harder to track than cookie-less identifiers?

**Comment by englehardt** [comment]
> This suggests that many sites detect when cookies are blocked, and react accordingly. I wonder if blocking cookies might trigger code on the part of trackers to use other, cookie-less tracking mechanisms - e.g., fingerprinting

Since this is only for Facebook cookies, I don't think we'd see those warnings. (It would be interesting if we did, since that might mean that Facebook's involved in displaying those messages).

If we block cookies I suspect we'll see the same amount of breakage in terms of Facebook login as we currently see from the container. i.e. the logins that still work don't require third-party cookies from Facebook. It's unclear to me how Facebook like and share buttons currently work on sites where the Facebook login flow succeeds?

Clearing cookies at the end of each session will still help remove the value of linking non-container cookies to container cookies (https://github.com/mozilla/contain-facebook/issues/74#issuecomment-377586113), even if Facebook gets some value by doing so within the session.

**Comment by stoically** [comment]
> I wonder if blocking cookies might trigger code on the part of trackers to use other, cookie-less tracking mechanisms - e.g., fingerprinting.

If that's the case that'd be indeed a really good point against blocking. I guess from a fingerprinting perspective would blocking also make Facebook Container users probably more unique (especially if they have a loggedin session in the fb container). So, I'm actually against implementing it, though it could be an option - not sure if that's something that is in the scope of the Add-on?

> It's unclear to me how Facebook like and share buttons currently work on sites where the Facebook login flow succeeds?

Afaik they pass all relevant tokens as GET query parameters

**Comment by groovecoder** [comment]
Based on the comments here, and the fact that we have other platform-level plans for improving cookie and other stateful tracking protections in Firefox, I'm going to close this PR as out-of-scope for the add-on right now.

Thanks all for the help and discussion!

**Pull request closed without merging**
