### PR TITLE
Maintain tab states: active, index

### LINKED ISSUE #19: Middle-click on a facebook link opens in a foreground tab (instead of background)
Middleclicking a facebook link results in a new facebook tab container which then gets focus. In the middle click case, the tab usually loads in the background.  Maybe we WANT the foreground to show the container switch, but it feels a bit janky as a user used to middle clicking links.

### LINKED ISSUE #56: Maintain tab order when switching containers
From email:

> Whenever I navigate to facebook, it seems to close the current tab, and create a new tab at the end of all the tabs that are open.
> 
> This is quite annoying when I have multiple tabs open and I want facebook to be at a certain position, and not having to scroll to the end all the time.

I think this is because when we switch we:
 browser.tabs.create({url: requestUrl.toString(), cookieStoreId: facebookCookieStoreId});
browser.tabs.remove(options.tabId);

IE create a new tab and delete the old one.  (meaning that we get tab on the right most edge). Can we control tab ordering with web extensions? Not sure? Could we just re-use the existing tabId when we swtich?

### PR DESCRIPTION
**Pull request by stoically**
Fixes #19, Fixes #56 and active status mentioned in #63

### CODE REVIEW

**Comment by groovecoder** [comment]
The fix for number https://github.com/mozilla/contain-facebook/issues/63 seems break links going outside of facebook? Puts it into an infinite tab open+close loop?

maintain-tab-state

**Comment by groovecoder** [comment]
@stoically if you re-base this on the commits/fixes for https://github.com/mozilla/contain-facebook/pull/55 it might fix this issue?

**Comment by stoically** [comment]
@groovecoder Did I understood you correctly that you experience an infinite loop with current HEAD and just this PR? I can't seem to reproduce that. Do you maybe have some more details how I can reproduce? Also I can't see the gif, it's just a black bar for me.

**Comment by stoically** [comment]
Nevermind, I can reproduce now. I'll look into it.

**Comment by stoically** [comment]
@groovecoder Fixed it. Passing in `openerTabId` seems to force the tab being created into the same cookieStoreId that the openerTabId was in, even when defining an explicit `cookieStoreId: 'firefox-default'` - resulting in an infinite loop. This doesn't seem exactly expected behavior, at least from my perspective.

I have to admit though, I only tested `active` and `index` and just added `openerTabId` because I've remembered that being done in MAC in a recent PR. Should've tested that, sorry.

**Comment by groovecoder** [comment]
Yup, this looks good and works well now. Thanks @stoically !

**Comment by stoically** [comment]
Thanks for merging!

**Pull request merged**
