### PR TITLE
fix #124: add whatsapp domains

### LINKED ISSUE #124: Add whatsapp domain to 1.4.0
- Is "Firefox will: Never remember history" in the Firefox Preferences/Options under "Privacy & Security > History" selected? Yes/No:
- Are you using Firefox in a Private Window? Yes/No:
- Can you see a grayed out but ticked Checkbox with the description "Enable Container Tabs" in the Firefox Preferences/Options under "Tabs"? Yes/No:
- Facebook Container Version:
- Operating System + Version:
- Firefox Version:
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
..

### Expected behavior
..

### Steps to reproduce
1. ..
2. ..
3. ..

### Notes
..

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by jonathanKingston** [comment]
Looks familiar :D I think there is some CDN urls missing though. I can't remember what they are though.

**Comment by pdehaan** [comment]
Probably missing [at least] **cdn.whatsapp.net**, per #104.

**Comment by SoftVision-PaulOiegas** [comment]
@groovecoder just quickly verified this with a build from master. Everything seems to be working OK except #104. When you right click an image from www.whatsapp.com page and you chose to "View Background Image", the URL looks like `https://www-cdn.whatsapp.net`. 
It seems that because it has hyphen between the www and cdn, it's not considered as a Facebook Container URL. And if you replace the hyphen with a dot, it works like a charm.

**Comment by jonathanKingston** [comment]
@SoftVision-PaulOiegas does this fix it: 
[facebook_container-1.4.0.zip](https://github.com/mozilla/contain-facebook/files/1907439/facebook_container-1.4.0.zip)

**Pull request merged**
