### PR TITLE
workaround to fix the dark theme icon issue

### LINKED ISSUE #217: The wrong webextension menupanel image is displayed
**[Affected versions]:**

- Firefox 65.0.2 (BuildId:20190225143501).
- Firefox 66.0 (BuildId:20190314174725).
- Firefox 67.0b3 (BuildId:20190318154932).
- Firefox 68.0a1 (BuildId:20190318213844).

**[Affected Platforms]:**

- Windows 10 64bit
- macOS 10.13
- Ubuntu 16.04 64bit

**[Steps to reproduce]:**

1. Launch Firefox.
2. Install Facebook Container 1.6.0
3. Observe the Webextension menupanel's image.

**[Expected result]:**

The menupanel's image is displayed as in: https://mozilla.invisionapp.com/share/NCQW7QI4FM9#/screens/350966779

**[Actual result]:**

The wrong Webextension menupanel image is displayed.

**[Additional Notes]:**
Attached screenshots for this:.

Light theme:
ic
Dark theme:
ic2

### PR DESCRIPTION
**Pull request by nemoload**
fixes #217

### CODE REVIEW

**Comment by nemoload** [comment]
@ShivangiKakkar  This issue is related to the SVG file of the icon itself. Feel free to edit it.

**Comment by ShivangiKakkar** [comment]
> @ShivangiKakkar This issue is related to the SVG file of the icon itself. Feel free to edit it.

Yes, I am looking into it. Not that experienced with the svg's. :(

**Comment by nemoload** [comment]
> Yes, I am looking into it. Not that experienced with the svg's. :(
Me neither.

**Comment by groovecoder** [comment]
@ShivangiKakkar feel free to ping epang or ron for help with SVG edits.

**Comment by groovecoder** [comment]
Superseded by https://github.com/mozilla/contain-facebook/pull/226. Thanks @nemoload for the contribution.

**Pull request closed without merging**
