### PR TITLE
Handle Multi-Account Containers Assignment edge-cases

### LINKED ISSUE #40: Explicitly assigning Facebook to Facebook Container from MAC menu will make the user end up with 2 opened Facebook tabs at each visit
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- Have the Firefox Multi-Account Containers add-on (6.0.0) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the https://www.facebook.com/ and click the "Multi-Account Containers" toolbar button.
3. Check the "Always open in Facebook" option and navigate to https://www.facebook.com/ in a new tab.
4. In the container confirmation tab check the "Remember my decision for this site" option.
5. Click the "Open in Facebook Container" button.
6. Open a new tab and navigate to Facebook.

**[Expected result]:**
- A single Facebook container tab is opened and the page is correctly loaded.

**[Actual result]:**
- Two Facebook container tabs are opened and the page is loaded in both.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
rec of the issue

### LINKED ISSUE #59: Does this require Multi-Account Containers to be installed and active?
When I first installed the Facebook Container extension, it didn't work, even after restarting the browser. I had to activate Multi-Account Containers, then deactivate and reactivate Facebook Container, to get the expected behavior.

That's OK (though I don't entirely see why it's necessary) but it's not clearly documented. The [blog post](https://blog.mozilla.org/firefox/facebook-container-extension/) didn't make that clear at all, and the README in this repo actually seems to indicate that Multi-Account Containers is _not_ a requirement, but is an additional option if you like Facebook Container.

So if it's intentional that Multi-Account Containers is required to use Facebook Container, it should be clearly documented. If it's not intentional, it does appear to be a requirement at the moment.

### PR DESCRIPTION
**Pull request by stoically**
Handle cases where Facebook is assigned or unassigned to "Always open in" using Multi-Account Containers after installation/enabling of contain-facebook or browser-start. To achieve this it was necessary to change the initialization behavior. The request handler is now always set-up and the check for MAC assignment always happens in the request handlers if it's an FACEBOOK_DOMAIN. Cookies are always cleared on initialization, regardless of MAC assignment. A side-effect is that, if just one specific domain is assigned with MAC, all other FACEBOOK_DOMAINS will still get contained from contain-facebook.

Also makes sure (by awaiting) that the Facebook container is correctly detected or created and hence should avoid that [this](https://github.com/stoically/contain-facebook/blob/1cceca2ccafc28b31dd1c5054ad717b2a5c4488b/background.js#L129-L130) happens.

Fixes #40, Fixes #59 and https://github.com/mozilla/contain-facebook/issues/23#issuecomment-376572752

### CODE REVIEW

**Comment by groovecoder** [comment]
This seems like a really good code change, but it conflicts with master now that https://github.com/mozilla/contain-facebook/pull/64 is merged.

**Comment by stoically** [comment]
@groovecoder Thanks. I've resolved the conflict.

**Comment by groovecoder** [comment]
Hah, you beat me to it! I'll run this branch thru a spot-check.

**Comment by stoically** [comment]
Thanks for merging. Unfortunately got the patch in #44 lost while resolving the conflict. Opened #69 to fix it again.

**Pull request merged**
