### PR TITLE
Prevent redirects and MAC-incompatibility from opening two tabs

### LINKED ISSUE #41: Two tabs with the same website are wrongly opened when trying to log in on it with Facebook, if the website was previously assigned to a container
**[Notes]:**
- If at step 2 the "Remember my decision for this site" option was not checked then the user will end with two confirmation windows.
- Even if you are not logged in to Facebook, after following the normal log in flow, you will encounter the same issue.

**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Facebook Container" add-on (1.2.3) installed.
- You must be logged in to Facebook.
- Have the Firefox Multi-Account Containers add-on (6.0.0) installed.
- Have the any website assigned that has the "Log In with Facebook" option to any container (eg. https://9gag.com to Work).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://9gag.com and check the "Remember my decision for this site" option.
3. Press the "Open in Work Container" option.
4. Click the "Log In" button and select the "Facebook" option.
5. Observe the behavior.

**[Expected result]:**
- You are successfully logged in.

**[Actual result]:**
- You are successfully logged in but also two tabs with the same website are opened.

**[Additional Notes]:**
- The issue is reproducible with any website that has the "Log In with Facebook" option.
- Attached a screen recording of the issue: 
rec of the issue

### LINKED ISSUE #48: Duplicate tabs opening
When a non-Facebook URL is typed into the address bar, the existing tab will go to the page but switch from the Facebook container to the default container. However, a duplicate tab will also open with that same URL.

### PR DESCRIPTION
**Pull request by stoically**
#55

Fixes #48, Fixes #41

### CODE REVIEW

**Comment by groovecoder** [comment]
Hmm ... on this branch I still got 2 tabs from a redirect to an assigned site.

1. Assign gsuite.google.com to always open in a container (I used "Work")
2. Go to facebook.com
  * [ ] Should be re-opened into Facebook container
3. In the location bar of the facebook container tab on facebook.com, go to gsuite.google.com

I still see 2 gsuite.google.com tabs open.

prevent-tab-duplication

**Comment by stoically** [comment]
@groovecoder Yes, this can happen because the same patch in MAC isn't published. You shouldn't experience this anymore if you test with MAC HEAD.

**Comment by groovecoder** [comment]
Ah, since this needs a MAC release I'm going to bump it from 1.2.5 to 1.3.0

**Comment by stoically** [comment]
Well, the fix in this PR prevents duplicate tabs for users that haven't MAC installed. So the fix itself is already useful for non-MAC users and doesn't rely on a MAC release.

However, I just realized something regarding the combination of contain-facebook and MAC:

In your scenario the contain-facebook isolation takes place; so contain-facebook will create a new tab. But at the same time MAC sees the same request and also decides to reopen into a new tab. The fix here is to *always* check for MAC assignment and don't do anything if the request URL is assigned, because MAC will handle it.

**Comment by stoically** [comment]
I've changed the [PR accordingly](https://github.com/stoically/contain-facebook/blob/dfe87fe19b5a04295ac2ff1e6de13ce6508c437b/background.js#L153-L161) to address the mentioned contain-facebook and MAC incompatibility. So users would already have a great benefit even without MAC release.

**Comment by stoically** [comment]
Thanks for the merge. Rebased #78 accordingly.

**Pull request merged**
