### PR TITLE
Add more facebook domains 45

### LINKED ISSUE #45: Include other facebook domains: instagram, whatsapp and messenger
https://instagram.com
https://messenger.com
WhatsApp web client

### PR DESCRIPTION
**Pull request by groovecoder**
Combines https://github.com/mozilla/contain-facebook/pull/42 and https://github.com/mozilla/contain-facebook/pull/46. Thanks @perflyst and @rosslh !

Fixes #45

### CODE REVIEW

**Comment by groovecoder** [comment]
@pdehaan and/or @SoftVision-PaulOiegas please check this PR branch?

**Comment by groovecoder** [comment]
Should we make some UX changes so users aren't confused why "Instagram" and "WhatsApp" and Messenger are contained in the "Facebook" Container?

**Comment by Perflyst** [comment]
I don't think they all belong to one company, Facebook. Normally everyone knows that and who didn't know it might think again about whether e.g. Whatsapp should be used for confidential conversations.

**Comment by ryanfeeley** [comment]
I wonder what other sites work as I noticed that https://secure.facebook.com/ works.

**Comment by stoically** [comment]
@ryanfeeley All sites listed in `FACEBOOK_DOMAINS` and all their subdomains work. So `facebook.com`, `fb.com`, `*.facebook.com` and `*.fb.com`.

(Actually, also [some more sites "work"](https://github.com/mozilla/contain-facebook/pull/44), but I guess that's not exactly intentional)

**Comment by ryanfeeley** [comment]
@stoically Great, thanks!

**Comment by Noah-Huppert** [comment]
Anything blocking this PR being merged in that I can help with?

**Comment by Noah-Huppert** [comment]
Excellent, can't wait.

**Comment by klaude** [comment]
Can we make non Facebook and messenger domains configurable or give some kind of notification explaining why IG and WhatsApp load in the container? 

I think it's important to keep a distinction between Facebook the service and Facebook the company. Users need to know Facebook owns Instagram and WhatsApp, but I think loading those two sites in a "Facebook" named container presents a confusing user experience.

**Comment by orium** [comment]
> Can we make non Facebook and messenger domains configurable or give some kind of notification explaining why IG and WhatsApp load in the container?

I think it should not be configurable as it defeats the point of this addon to isolate facebook.

IMO the best UX would be that for first time the user opens something like "instagram.com" a notification would show up explaining why that tab is in the facebook cointainer.  That notification would have a "do not show again" checkbox.

**Comment by TanviHacks** [comment]
@groovecoder lets go with the domains in this PR for now - merge and start testing on 1.3.0.  Thanks!

**Comment by groovecoder** [comment]
Now that https://github.com/mozilla/contain-facebook/pull/94 is merged, I started testing on this branch and saw that we *MUST* add `atdmt.com` to the list - it is [*the* 3rd-party tracking cookie used by Atlas/Facebook](https://en.wikipedia.org/wiki/Atdmt), beyond just the facebook.com cookies.

**Comment by oddmean** [comment]
What about Facebook's .onion domains?

**Comment by groovecoder** [comment]
Interesting. I suppose we could add it, but Tor browser strongly suggests *against* installing add-ons, and the First-Party Isolation protection provided by Tor browser has the same effect. So it's possible, but not a priority.

**Comment by stoically** [comment]
@groovecoder  Since Tor Browser is on 52 ESR which doesn't support Containers, adding onion domains wouldn't be relevant for Tor Browser users - but for users that manually configure Tor for an up-to-date Firefox (e.g. with Proxy Switcher per Domain).

**Comment by oddmean** [comment]
Not only Tor browser may be used to access .onion sites. In my case it's Firefox 59.0.2 with a separate profile fine-tuned for privacy means. Using a separate profile for Tor I still make use of Multi-Account Containers to isolate logins and and "obfuscate my footprints" on the Internet.

**Comment by krystian3w** [comment]
Add `fb.me`

**Pull request merged**
