### PR TITLE
add official facebook tor/onion domains

### LINKED ISSUE #111: Feature request: Add `facebookcorewwwi.onion`
As can be read in [this Facebook release notes post](https://www.facebook.com/notes/protect-the-graph/making-connections-to-facebook-more-secure/1526085754298237/), which is linked from [the article about Tor on Cloudflare’s blog](https://blog.cloudflare.com/the-trouble-with-tor/), Facebook uses the <code title="Facebook Core World Wide Web Infrastructure">https://<wbr/>facebookcorewwwi<wbr/>.onion/</code> address for better user experience for users of the Tor browser.

### LINKED ISSUE #146: https://facebookcorewwwi.onion official tor hidden service not contained
made a pr here but there may be more domains to add:  https://github.com/mozilla/contain-facebook/pull/147

### Actual behavior
.. not contained

### Expected behavior
.. contain the onion version of facebook

### Steps to reproduce
1. .. run tor browser available at torproject.org
2. .. go to https://facebookcorewwwi.onion or https://m.facebookcorewwwi.onion mobile subdomain

### Notes
.. it is an official facebook onion hidden service with various subdomains and also fbcdn equivalents:

facebookcorewwwi.onion
m.facebookcorewwwi.onion
lm.facebookcorewwwi.onion
l.facebookcorewwwi.onion
fbcdn23dssr3jqnq.onion
... and more

### PR DESCRIPTION
**Pull request by hairetikos**
fixes #111 
fixes #146 

there may be more domains to add, not 100% sure

### CODE REVIEW

**Comment by doronbehar** [comment]
So what is the status of this PR?

**Comment by ExE-Boss** [comment]
Someone from Mozilla needs to merge it.

review?(@groovecoder)

**Comment by groovecoder** [comment]
Thanks for the submission, but we don't plan to support `.onion` domains with this extension. We don't want to encourage Tor browser users to install extensions, and Tor has first-party isolation which effects the same protection as Facebook Container.

**Comment by hairetikos** [comment]
@groovecoder 

this plugin is specifically to "contain facebook",

not everyone who uses tor is using the tor browser.

when using the regular firefox browser with tor as a socks proxy, this plugin would be beneficial.

nevermind.

**Comment by doronbehar** [comment]
I see it the same way.

I don't use the tor browser but I do use a normal firefox and sometimes with the tor proxy to browse specific websites, obviously `.onion`.. (I use [SmartProxy](https://addons.mozilla.org/en-US/firefox/addon/smartproxy/) to be specific)

Having that domain onion domain in our list could have been beneficial and it certainly wouldn't harm any non tor users.

Should I fork this repo?

**Comment by groovecoder** [comment]
That makes sense - please make a fork for it.

Currently re: Tor, Mozilla suggests the whole Tor Browser Bundle with no extensions, so we'll keep this add-on inline with that suggestion.

But, an onion-inclusive add-on is a good idea.

**Comment by doronbehar** [comment]
Generally BTW, I was thinking about problems like this and very much like any other domain requests and I reached the conclusion that a new addon should be created that will enable a user to configure matches of arbitrary containers to arbitrary domains - think of a general addon that will provide the same functionality provided by this addon and other container addons, like [Amazon container](https://addons.mozilla.org/en-US/firefox/addon/amazon-container/) and [Reddit container](https://addons.mozilla.org/en-US/firefox/addon/reddit-container/), or the [Ebay container](https://addons.mozilla.org/en-US/firefox/addon/ebay-container/) only with user interface to configure the matches of the domains to the various containers.

I'll let the Mozilla guys (@hairetikos) think about what we say here, if they won't change their minds I'll fork and post it at https://addons.mozilla.org and notify here.

Someday I'll might find the time to work on the general addon that I was describing.. :)

**Comment by doronbehar** [comment]
Thanks for your feedback @groovecoder , I have tested [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/) and (correct me if I'm wrong but) the difference between this and what I'm talking about is that my addon shall **automatically switch to the correct** container based on the URL, just like all the container addons I've mentioned above.

The [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/) unfortunately doesn't do that but perhaps instead of creating a new addon, creating a PR for [Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/) that will add this functionality could be sufficient...

**Comment by groovecoder** [comment]
You're right - MAC doesn't have built-in automatic containment, and I don't think we'll ever add that feature to MAC. (It's why we made a separate Facebook Container from MAC).

So, I think a separate auto-contain-big-tech-companies add-on is a good idea and actually has its own target audience too. I say go for it!

**Comment by luixxiul** [comment]
FYI `onion` sites become also available on Firefox by toggling the preference `network.dns.blockDotOnion` on `about:config`. https://github.com/mozilla/contain-facebook/issues/111#issuecomment-384163110

Will this PR nevertheless not be merged based on https://github.com/mozilla/contain-facebook/pull/147#issuecomment-426678003?

**Comment by groovecoder** [comment]
Correct - we won't plan to merge this for the foreseeable future.

**Comment by xaiki** [comment]
maybe this issue should take the user to a 'YOU SHOULD NOT USE THIS EXTENSION IF USING TOR' because right now it silently defaults to not containing.

**Pull request closed without merging**
