### PR TITLE
Add Oculus domains

### PR DESCRIPTION
**Pull request by mnafees**

### CODE REVIEW

**Comment by esaruoho** [comment]
what are these conflicts going on in background.js, btw?

**Comment by esaruoho** [comment]
query, couldn't this PR be simplified so it just references oculus.com instead of subdomainsgalore.oculus.com ?

**Comment by esaruoho** [comment]
@mnafees can you fix the `src/background.js` conflicts caused by this PR, please?

**Comment by esaruoho** [comment]
@mnafees looks like there are linting errors.

```
/home/travis/build/mozilla/contain-facebook/src/background.js
  13:1  error  Expected indentation of 2 spaces but found 4  indent
  14:1  error  Expected indentation of 2 spaces but found 4  indent
```

also, you only need to mention oculus.com once, not allsubdomainsof.oculus.com :)

**Comment by mnafees** [comment]
> 
> 
> @mnafees looks like there are linting errors.
> 
> ```
> /home/travis/build/mozilla/contain-facebook/src/background.js
>   13:1  error  Expected indentation of 2 spaces but found 4  indent
>   14:1  error  Expected indentation of 2 spaces but found 4  indent
> ```
> 
> also, you only need to mention oculus.com once, not allsubdomainsof.oculus.com :)

Oh? I saw the multiple subdomains for fb and whatsapp so I presumed that I have to mentionall the subdomains :P Thanks for pointing out!

**Comment by esaruoho** [comment]
@groovecoder @groovecoder-mozilla-owner looks like this is pretty much ready to land? :)

**Comment by groovecoder** [comment]
@ShivangiKakkar - do you have any time/opportunity to do a quick spot-check on this branch of Facebook Container? Just make sure the main Facebook, Instagram, Messenger, and WhatsApp sites still work with this change?

**Comment by ShivangiKakkar** [comment]
@groovecoder Yes, I would love to :). Okay, Let me check.

**Comment by ShivangiKakkar** [comment]
@groovecoder sorry was stuck with other issues, checking it now! :)

**Comment by ShivangiKakkar** [comment]
@groovecoder  I did a spot-check on @mnafees branch and all urls seems to open in the containers with the changes in this PR.

**Comment by esaruoho** [comment]
looks like @ShivangiKakkar approves of this branch and it's changes, @groovecoder @groovecoder-mozilla-owner  - any chance this could land?

**Comment by groovecoder** [comment]
Thanks @ShivangiKakkar and @esaruoho.

**Pull request merged**
