### PR TITLE
Clearing serviceWorkers for domains as they capture the navigation in…

### LINKED ISSUE #101: The "web.whatsapp.com" page doesn't open in a Facebook Container if the website was visited before installing Facebook Container
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- A new profile was created and the "https://web.whatsapp.com/" page was never visited.
- Have the "xpinstall.signatures.required" pref set to "false".

**[Steps to reproduce]:**
1. Open the Firefox browser and navigate to https://web.whatsapp.com/.
2. Navigate to "about:addons" -> Extensions tab and install the Facebook Container v1.3.0.
3. Open a new tab.
4. Navigate to https://web.whatsapp.com/ and observe the behavior.

**[Expected result]:**
- The page is opened in Facebook container.

**[Actual result]:**
- The page is opened in normal tab.

**[Notes]:**
- This issue is also reproducible after you restart the browser.
- If you try to open the page in a default container, it will be opened in a Facebook container. However, if you open a new tab and navigate to https://web.whatsapp.com/, the page will again be loaded in a non-container tab.
- Here is a screen recording of the issue:
fb container - webwhatsapp normal tab

### PR DESCRIPTION
**Pull request by jonathanKingston**
…stead. Fixes #101

### CODE REVIEW

**Comment by groovecoder** [comment]
I like this, but I think we should punt anything WhatsApp to a 1.4.x release.

**Comment by jonathanKingston** [comment]
@groovecoder did you mean to merge this into 1.3.1? It didn't get released there?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @jonathanKingston @groovecoder. I was trying to make some custom builds today from the branches where things got fixed/changed, including this one. But any attempt failed due to `manifest.json` file not found.

Has the building process changed? I used `git clone https://github.com/mozilla/contain-facebook` + `web-ext build` for master. and `git clone -b <branch_name> <repo>` + `web-ext build` for separate branches.

**Comment by SoftVision-PaulOiegas** [comment]
Found out that I can cd to `/src` folder where the `manigfest.json` file is and build it from there. However, doesn't seem to be fixing the #101 issue since I get the same result when executing the steps from it.

**Comment by jonathanKingston** [comment]
@SoftVision-PaulOiegas this didn't get merged properly see my last comment. Instead https://github.com/mozilla/contain-facebook/pull/128 solves this too. Alternatively you would have to manually check out this branch perhaps.

**Pull request merged**
